# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Software Engineering by Thomas Prochazka
author: Thomas Prochazka
email: thomas.prochazka@gmail.com
description: A little Software Engineering Blog by Thomas Prochazka, filled with posts regarding engineering problems and solutions
keywords: "Software Engineer, Software Development, Blog"
profile_icon_hash: 52a73317cd435a835d6cc927959f988c
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zlypher.github.io" # the base hostname & protocol for your site, e.g. http://example.com
ga_tracking_id: UA-108482569-1

permalink: /posts/:title
paginate: 3
paginate_path: "/posts/:num/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: _sass

collections:
  people:
    output: true
  projects:
  experience:

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude: [vendor]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
